version: "3"

services:
  app:
    build: .
    command: yarn dev:server
    ports:
      - "3333:3333" 
    volumes:
      - .:/user/app

  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgre"
      
    ports:
      - "5432:5432"
    volumes:
      - /home/duducp/PostgreSQL:/var/lib/postgresql/data